services:
  app:
    image: nginx:alpine
    container_name: app
    restart: unless-stopped
    volumes:
      - ./app:/usr/share/nginx/html:ro
    expose:
      - "3000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - /home/frede/swift-secrets/cloudflared:/etc/cloudflared
    depends_on:
      - app
